### ISSUE TITLE
Feature idea: Something for the Hunters

### ISSUE THREAD

**Issue by TheGrayAlien** [orendain/DemeoMods#317]
I'm working on a custom ruleset that adds a new permanent ability to each class and so far I've got them all except the Hunter. The only AbilityKey I can see as an option is ThornPowder, which would work out great, but for some reason that appears to be one of the only abilities that isn't allowed to hit non-players. Is there a way to make a rule that changes this? It also appears there's no current way to have more than 2 replenishable abilities per Hero. Can that also be modified? I realize this is a personal request but it may come up again as the game progresses. Thanks!

**Comment by jimconner** [comment]
Each Ability has a list of `ValidAbilityTargets` which controls where that ability may be used. For ThornPowder, it is restricted to Players, Props & Pets 
![image](https://user-images.githubusercontent.com/9944861/165584653-cc9b0c25-7715-4783-af97-fd13306a06b9.png)

It would be very straightforward to make a skirmish-only rule (the code would be near identical to AbilityRandomPieceList) but I don't think this can be made to work in multiplayer games properly. I'm pretty sure that at some point I actually made a rule for this, but discovered that clients could still only target the same things as before.

More than 2 replenishables per hero will be fixed in the next patch of Demeo. Our friendly modding-community rep from RG (Kyhperia) let us know that she's worked a fix into v1.15 of demeo for when it releases.

**Comment by TheGrayAlien** [comment]
Ok, thanks again for your quick responses to my issue reports. That's great news about the replenishables! I think I've worked out some bonuses for my Hunter class changes that will balance it out with the extra replenishables given to the other classes in my ruleset, for now, until we're allowed to use more than 2. =)

**Comment by jimconner** [comment]
The v1.15 patch for Demeo, and corresponding PR for HouseRules means that it is now possible to have more than 2 replenishables. Closing this ticket becuase there's nothing else left to do here now.
