### ISSUE TITLE
AbilityDamageOverriddenRule does not allow setting of splashDamage and critSplashDamage

### ISSUE THREAD

**Issue by jimconner** [orendain/DemeoMods#322]
When attempting to adjust AoE abilities such as Whirlwind and Charge, changes applied with `AbilityDamageOverriddenRule` do not work correctly. The card shows the correct values for `targetDamage` and `critDamage` but the damage dealt to enemies is unchanged from the defaults.

Upon investigation it appears that the the AoE attacks for Whirlwind and Charge are dealing `splashDamage` and `critSplashDamage` to enemies. The AbilityDamageOverriddenRule does not currently allow for setting of these fields.

Thanks to The Gray Alien for reporting this issue.

**Comment by orendain** [comment]
At first thought, three approaches come to mind. In no particular order:

1. Extend the 2-element array to 4-element array, where each of the 4 types of damage are specified.
    - Pros: Single rule
    - Cons: It will be tricky for users to specify, for example, splash and crit splash damage while not wanting to specify regular damage.
2. Modify the rule to accept a struct type, rather than a list/array. For example, like `PieceProperty` in `PieceConfigAdjustedRule`.
    - Pros: Users may specify only the damage types they want.
    - Cons: Additional verbosity in ruleset configs. I.e., no longer `[3, 6]`, but rather `{ TargetDamage = 3, CritDamage = 6 }`
3. Create a separate rule for splash damage.

WDYT?

**Comment by jimconner** [comment]
I think that option 2 is the best one. Not all attacks have splash damage, so having to specify a list of 4 numbers would be confusing. I don't think that the verbosity in the ruleset is too much of a con.

**Comment by TheGrayAlien** [comment]
Just wondering if it might have been easier to change this rule to be Adjusted instead of Overridden? Then you could go with option 1 and use 4 parameters because if you want no damage change you just put in a 0 instead of having to define the damage number, which would keep in line with AbilityAoeAdjusted.
