### ISSUE TITLE
House Rules: Demeo Reloaded next level does not load

### ISSUE THREAD

**Issue by McFredward** [orendain/DemeoMods#414]
Apparently [this merge](https://github.com/orendain/DemeoMods/pull/392) did not fixed the bug in House Rules *Demeo Reloaded*. We've tried today 3 times and every time the game does not load the shopping-level after triying to activate the final-door in the first floor.

We were 4 players with 2PCVR and 2 Quest-only users. We've also tried to choose different books at the beginning, which also results in the same game-breaking bug.
If the bug appears directly after activating the door with the key, the game does not freeze, but nobody can do anything anymore, not even closing the game in the menu, the buttons just dont react anymore. And the shopping room or any other level is not loaded. Everybody has to kill the Demeo process and fully restart.

Game Version: 1.19.165012
House Rules Version: 1.4.0
MelonLoader: 0.5.4

**Comment by jimconner** [comment]
Hi @McFredward - Thank you for submitting this bug report. We'll take a look and see if we can work out what's going wrong.

**Comment by TheGrayAlien** [comment]
The merge you listed should have fixed this issue since there have been no adjustments since and it's working every time in my testing. The problem initially was that the next floor's shop name was incorrect which cause the game to basically freeze while trying to load it. I suggest you get the latest working build here: https://github.com/orendain/DemeoMods/actions/runs/2723097282 then extract the zip'd DLL's into your Demeo and/or Demeo PC-Edition directories. Make sure to allow replacement of the old ones and check that they do indeed replace them.

**Comment by McFredward** [comment]
Thanks for your answer 👍 
Yes I've tried the new build, and it worked. So the issue was that the newest release v. 1.4.0 does not contain the fix.
